#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application('console', '1.0.0');
$application->add(new Fagai\LineData\Commands\GenerateCommand());
$application->run();

